parts:
  librelinkupdesktop:
    source: .
    plugin: npm
    npm-include-node: true
    npm-node-version: '20.11.1'
    build-packages:
      - curl
      - xz-utils
    override-build: |
      # Configure proxy for Electron download if a proxy is set
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      # Proceed with your original build commands
      npm install
      npm run prebuild
      npm run build
      npm run package
      cp -R dist/linux-unpacked $SNAPCRAFT_PART_INSTALL/librelinkupdesktop-linux-x64
    stage-packages:
      - libnss3
      - libnspr4
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libdbus-1-3
      - libexpat1
      - libxcb1
      - libxkbcommon0
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libasound2
      - libatspi2.0-0
      - libgtk-3-0
