name: librelinkupdesktop
base: core22
version: '0.1.3'
summary: Fetches your blood sugar from LibreLinkUp
description: |
  This is a desktop application that fetches your blood sugar from LibreLinkUp

confinement: strict
grade: stable

architectures:
  - build-on: amd64

apps:
  librelinkupdesktop:
    command: librelinkupdesktop/librelinkupdesktop --no-sandbox
    extensions: [gnome]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  librelinkupdesktop:
    plugin: nil
    source: .
    override-build: |
        # Configure proxy for Electron download if a proxy is set
        if [ -n "$http_proxy" ]; then
          export ELECTRON_GET_USE_PROXY=1
          export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
          export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        fi

        npm install electron @electron/packager
        npx electron-packager . librelinkupdesktop --overwrite --platform=linux --arch=x64 --out=release-build --prune=true --electron-version=27.3.4 --app-version=0.1.3
        cp -rv release-build/librelinkupdesktop-linux-x64 $SNAPCRAFT_PART_INSTALL/librelinkupdesktop
        chmod -R 755 $SNAPCRAFT_PART_INSTALL/librelinkupdesktop
    build-snaps:
    - node/20/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
