name: librelinkupdesktop
base: core22
version: '0.1.3'
summary: Fetches your blood sugar from LibreLinkUp
description: |
 This is a desktop application that fetches your blood sugar from LibreLinkUp

confinement: strict
grade: stable

architectures:
  - build-on: amd64

apps:
  librelinkupdesktop:
    command: librelinkupdesktop/librelinkupdesktop --no-sandbox
    extensions: [gnome]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIRx

parts:
  librelinkupdesktop:
    plugin: nil
    source: .
    override-build: |
        npm install electron @electron/packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./librelinkupdesktop-linux-* $SNAPCRAFT_PART_INSTALL/librelinkupdesktop
    build-snaps:
    - node/20/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
