name: librelinkupdesktop
base: core20
version: '0.1.3'
summary: Fetches your blood sugar from LibreLinkUp
description: |
 This is a desktop application that fetches your blood sugar from LibreLinkUp

confinement: strict
grade: stable

architectures:
  - build-on: amd64

apps:
  librelinkupdesktop:
    command: electron-launch $SNAP/librelinkupdesktop-linux-x64/librelinkupdesktop
    plugs: [home, x11, unity7, browser-support, network, gsettings, pulseaudio, opengl]

parts:
  librelinkupdesktop:
    source: .
    plugin: npm
    npm-node-version: '20.11.1'
    build-packages:
      - curl
      - xz-utils
    override-build: |
      # Configure proxy for Electron download if a proxy is set
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      # Download and extract Node.js
      curl -fsSL https://nodejs.org/dist/v20.11.1/node-v20.11.1-linux-x64.tar.xz | tar -xJv
      export PATH=$PWD/node-v20.11.1-linux-x64/bin:$PATH

      # Verify Node version
      node -v

      # Proceed with your original build commands
      npm install
    stage-packages:
      - libnss3
      - libnspr4
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libdbus-1-3
      - libexpat1
      - libxcb1
      - libxkbcommon0
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libasound2
      - libatspi2.0-0
      - libgtk-3-0
